---
- name: Test Conection to my server
  hosts: wms1.ordunet.ge
  become: yes

  tasks:

    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

#wms1.ordunet.ge
    - name: Check disk space on /dev/sdb1
      shell: df -h /mnt/disk-1 | awk 'NR==2 {print $5}'
      register: disk_sdb1

    - name: Check disk space on /dev/sdc1
      shell: df -h /mnt/disk-6 | awk 'NR==2 {print $5}'
      register: disk_sdc1

    - name: Check disk space on /dev/sdd1
      shell: df -h /mnt/disk-3 | awk 'NR==2 {print $5}'
      register: disk_sdd1

    - name: Check disk space on /dev/sde1
      shell: df -h /mnt/disk-4 | awk 'NR==2 {print $5}'
      register: disk_sde1

    - name: Check disk space on /dev/sdf1
      shell: df -h /mnt/disk-5 | awk 'NR==2 {print $5}'
      register: disk_sdf1

    - name: Check disk space on /dev/sdg1
      shell: df -h /mnt/disk-6 | awk 'NR==2 {print $5}'
      register: disk_sdg1

    - name: Check disk space on /dev/sdg1
      shell: df -h /mnt/disk-6 | awk 'NR==2 {print $5}'
      register: disk_sdg1



    - name: Send Telegram message if any disk is over 70%
      uri:
        url: "https://api.telegram.org/bot6171926622:AAHmnGXEtn_n5Ly7SzIYJUJiDmEzKi0NwNY/sendMessage"
        method: POST
        body_format: json
        body: '{"chat_id": "-819128834", "text": "Disk space on {{ inventory_hostname }} is above 70%!"}'
        headers:
          Content-Type: application/json
      when: disk_usage.stdout[:-1]|int > 70 or disk_sdb1.stdout[:-1]|int > 70 or  disk_sdc1.stdout[:-1]|int > 70 or disk_sde1.stdout[:-1]|int > 70 or disk_sdf1.stdout[:-1]|int > 70 or disk_sdd1.stdout[:-1]|int > 70 or disk_sdg1.stdout[:-1]|int > 70
